# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/njazz/Documents/github/paulstretchlib/lib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/njazz/Documents/github/paulstretchlib/submodules/portaudio/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/njazz/Documents/github/paulstretchlib/submodules/portaudio/cmake_support/portaudio-2.0.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/CheckIncludeFileCXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/CheckTypeSize.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.16.4/share/cmake/Modules/TestBigEndian.cmake))

/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.16.4/bin/cmake -H/Users/njazz/Documents/github/paulstretchlib/app-cxx -B/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode
