# CMake generated Testfile for 
# Source directory: /Users/njazz/Documents/github/paulstretchlib/submodules/flac/test
# Build directory: /Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(libFLAC "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_libFLAC.sh")
  set_tests_properties(libFLAC PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;14;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(libFLAC "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_libFLAC.sh")
  set_tests_properties(libFLAC PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;14;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(libFLAC "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_libFLAC.sh")
  set_tests_properties(libFLAC PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;14;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(libFLAC "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_libFLAC.sh")
  set_tests_properties(libFLAC PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;14;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
else()
  add_test(libFLAC NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(grabbag "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_grabbag.sh")
  set_tests_properties(grabbag PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;24;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(grabbag "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_grabbag.sh")
  set_tests_properties(grabbag PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;24;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(grabbag "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_grabbag.sh")
  set_tests_properties(grabbag PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;24;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(grabbag "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_grabbag.sh")
  set_tests_properties(grabbag PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;24;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
else()
  add_test(grabbag NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(flac "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_flac.sh")
  set_tests_properties(flac PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;27;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(flac "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_flac.sh")
  set_tests_properties(flac PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;27;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(flac "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_flac.sh")
  set_tests_properties(flac PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;27;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(flac "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_flac.sh")
  set_tests_properties(flac PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;27;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
else()
  add_test(flac NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(metaflac "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_metaflac.sh")
  set_tests_properties(metaflac PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;31;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(metaflac "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_metaflac.sh")
  set_tests_properties(metaflac PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;31;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(metaflac "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_metaflac.sh")
  set_tests_properties(metaflac PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;31;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(metaflac "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_metaflac.sh")
  set_tests_properties(metaflac PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;31;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
else()
  add_test(metaflac NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(replaygain "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_replaygain.sh")
  set_tests_properties(replaygain PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;34;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(replaygain "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_replaygain.sh")
  set_tests_properties(replaygain PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;34;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(replaygain "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_replaygain.sh")
  set_tests_properties(replaygain PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;34;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(replaygain "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_replaygain.sh")
  set_tests_properties(replaygain PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;34;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
else()
  add_test(replaygain NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(seeking "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_seeking.sh")
  set_tests_properties(seeking PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;37;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(seeking "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_seeking.sh")
  set_tests_properties(seeking PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;37;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(seeking "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_seeking.sh")
  set_tests_properties(seeking PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;37;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(seeking "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_seeking.sh")
  set_tests_properties(seeking PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;37;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
else()
  add_test(seeking NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(streams "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_streams.sh")
  set_tests_properties(streams PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;40;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(streams "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_streams.sh")
  set_tests_properties(streams PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;40;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(streams "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_streams.sh")
  set_tests_properties(streams PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;40;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(streams "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_streams.sh")
  set_tests_properties(streams PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;40;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
else()
  add_test(streams NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(compression "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_compression.sh")
  set_tests_properties(compression PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;45;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(compression "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_compression.sh")
  set_tests_properties(compression PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;45;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(compression "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_compression.sh")
  set_tests_properties(compression PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;45;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(compression "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/test_compression.sh")
  set_tests_properties(compression PROPERTIES  ENVIRONMENT "ECHO_C=\\c" WORKING_DIRECTORY "/Users/njazz/Documents/github/paulstretchlib/app-cxx/xcode/pslib/FLAC/test" _BACKTRACE_TRIPLES "/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;45;add_test;/Users/njazz/Documents/github/paulstretchlib/submodules/flac/test/CMakeLists.txt;0;")
else()
  add_test(compression NOT_AVAILABLE)
endif()
